"""Database engine and migration runner.

SQLite by default (Phase 1); point AWA_DATABASE_URL at Postgres for the
multi-client deployment. All SQL in the platform is portable across both.
"""

from __future__ import annotations

import os
from pathlib import Path

from sqlalchemy import Engine, create_engine, text

MIGRATIONS_DIR = Path(__file__).resolve().parents[2] / "migrations"

_engine: Engine | None = None


def database_url() -> str:
    return os.environ.get("AWA_DATABASE_URL", "sqlite:///awa.db")


def get_engine() -> Engine:
    global _engine
    if _engine is None:
        url = database_url()
        kwargs = {}
        if url.startswith("sqlite"):
            kwargs["connect_args"] = {"check_same_thread": False}
        _engine = create_engine(url, **kwargs)
    return _engine


def reset_engine() -> None:
    """Drop the cached engine (tests point AWA_DATABASE_URL elsewhere)."""
    global _engine
    if _engine is not None:
        _engine.dispose()
    _engine = None


def run_migrations(engine: Engine | None = None) -> list[str]:
    """Apply migrations/*.sql in name order, tracking what has run."""
    engine = engine or get_engine()
    applied: list[str] = []
    with engine.begin() as conn:
        conn.execute(text(
            "CREATE TABLE IF NOT EXISTS schema_migration ("
            "name TEXT PRIMARY KEY, applied_at TEXT NOT NULL)"
        ))
        done = {r[0] for r in conn.execute(text("SELECT name FROM schema_migration"))}
        for path in sorted(MIGRATIONS_DIR.glob("*.sql")):
            if path.name in done:
                continue
            sql = path.read_text()
            if engine.dialect.name == "postgresql":
                # SQLite's rowid-backed serial columns, expressed portably.
                sql = sql.replace(
                    "INTEGER PRIMARY KEY",
                    "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
            for statement in _split_statements(sql):
                conn.execute(text(statement))
            conn.execute(
                text("INSERT INTO schema_migration (name, applied_at) "
                     "VALUES (:n, datetime('now'))" if engine.dialect.name == "sqlite"
                     else "INSERT INTO schema_migration (name, applied_at) "
                          "VALUES (:n, now())"),
                {"n": path.name},
            )
            applied.append(path.name)
    return applied


def _split_statements(sql: str) -> list[str]:
    """Split a migration file on top-level semicolons, dropping comments."""
    lines = [l for l in sql.splitlines() if not l.strip().startswith("--")]
    statements = []
    for chunk in "\n".join(lines).split(";"):
        if chunk.strip():
            statements.append(chunk.strip())
    return statements
